export default {
    5: {padId: null, cc: "sampleStart"},
    6: {padId: null, cc: "sampleEnd"},
    7: {padId: null, cc: "gain"},
    8: {padId: null, cc: "detune"},
    36: {padId: 12, cc: "note"},
    37: {padId: 13, cc: "note"},
    38: {padId: 14, cc: "note"},
    39: {padId: 15, cc: "note"},
    40: {padId: 8, cc: "note"},
    41: {padId: 9, cc: "note"},
    42: {padId: 10, cc: "note"},
    43: {padId: 11, cc: "note"},
    44: {padId: 4, cc: "note"},
    45: {padId: 5, cc: "note"},
    46: {padId: 6, cc: "note"},
    47: {padId: 7, cc: "note"},
    48: {padId: 0, cc: "note"},
    49: {padId: 1, cc: "note"},
    50: {padId: 2, cc: "note"},
    51: {padId: 3, cc: "note"},
}